name: CRC Training Calculator - CD Pipeline

on:
  pull_request: 
    branches: [ main ]
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_suffix: linux
          - os: windows-latest
            artifact_suffix: windows
          - os: macos-latest
            artifact_suffix: macos

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Application
      run: |
        pyinstaller specs/CRCTrainingCalculator.spec

    - name: Create Zip Archive
      run: |
        cd dist
        if [ "${{ runner.os }}" == "Windows" ]; then
          zip CRCTrainingCalculator-v${{ github.run_number }}-${{ matrix.artifact_suffix }}.zip CRCTrainingCalculator.exe
        else
          zip CRCTrainingCalculator-v${{ github.run_number }}-${{ matrix.artifact_suffix }}.zip CRCTrainingCalculator
        fi
        cd ..

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/CRCTrainingCalculator-v${{ github.run_number }}-${{ matrix.artifact_suffix }}.zip
        token: ${{ secrets.GH_PAT }}
      #env:
      #  GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
