name: CRC Training Calculator - CD Pipeline

on:
  push:
    #branches:
    #  - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build Application
      run: |
        pyinstaller specs/CRCTrainingCalculator.spec

    - name: Create Zip Archive
      run: |
        cd dist
        zip CRCTrainingCalculator-v${{ github.run_number }}.zip CRCTrainingCalculator
        cd ..

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/CRCTrainingCalculator-v${{ github.run_number }}.zip
        token: ${{ secrets.GH_PAT }}
      #env:
      #  GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
